### ISSUE TITLE
Button border is enabled automatically if one of the Border colour is selected

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#403]
If you select one of the Border colours for a button (part of a Button group), that button has the border enabled automatically, even if the Border width is set to 0.

**Repro:**
1. Add a button group to the page
2. Enable a Border colour for that button
3. Make sure the Border width is set to 0
4. Preview the page and hover on the button

**Expected (state on hover):**
![image](https://user-images.githubusercontent.com/52494172/89626224-bbc7f700-d8a1-11ea-88d2-61a84e56f1e9.png)

**At the moment:**
![image](https://user-images.githubusercontent.com/52494172/89626292-d601d500-d8a1-11ea-865f-ce7a068c7a96.png)
![Screenshot 2020-08-07 at 11 34 11](https://user-images.githubusercontent.com/52494172/89627104-0433e480-d8a3-11ea-93a7-44658537df14.png)

Wp version: 5.4.2
Otter version: 1.5.6

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/commit/b1175cae5cd851feb42a0994adc4afa1e21a3ace

**Comment by selul** [comment]
this is still not working, setting border zero does not add the zero value, it's just removing the prop.

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/pull/482/commits/cf87352a4203f4ad0334019151c86a72e800be49
